### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by 19819068211** [Levitans/XueXiTongAutoFlush#27]
C:\Users\jl\Downloads\XueXiTongAutoFlush-master\XueXiTongAutoFlush-master>python faithlearning.py
Traceback (most recent call last):
  File "faithlearning.py", line 51, in <module>
    from package.learn import color, learn_helper, exception, no_secret
  File "C:\Users\jl\Downloads\XueXiTongAutoFlush-master\XueXiTongAutoFlush-master\package\learn\learn_helper.py", line 14, in <module>
    from package.learn.school import fuist
  File "C:\Users\jl\Downloads\XueXiTongAutoFlush-master\XueXiTongAutoFlush-master\package\learn\school\fuist.py", line 12, in <module>
    def get_courses(driver) -> list[Course]:
TypeError: 'type' object is not subscriptable

**Comment by Levitans** [comment]
closed中有有问题产生的原因，和解决方案你可以去看看

**Comment by Levitans** [comment]
就是你的python版本低了，要python3.9以上的
