### ISSUE TITLE
报错(Session info: chrome=99.0.4844.51)

### ISSUE THREAD

**Issue by 447238862** [Levitans/XueXiTongAutoFlush#7]
========================================
Traceback (most recent call last):
  File "D:\XueXiTongAutoFlush-master\main.py", line 137, in <module>
    coursesList = xueXiTong.getCourses()
  File "D:\XueXiTongAutoFlush-master\package\ControlWeb\xueXiTong.py", line 87, in getCourses
    return self.__school.getCourses()
  File "D:\XueXiTongAutoFlush-master\package\ControlWeb\school.py", line 26, in getCourses
    itemList = self.__driver.find_element(By.CSS_SELECTOR, '[class="course-list"]') \
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[class="course-list"]"}
  (Session info: chrome=99.0.4844.51)
Stacktrace:
Backtrace:
        Ordinal0 [0x004E9943+2595139]
        Ordinal0 [0x0047C9F1+2148849]
        Ordinal0 [0x00374528+1066280]
        Ordinal0 [0x003A0FD4+1249236]
        Ordinal0 [0x003A11CB+1249739]
        Ordinal0 [0x003CD812+1431570]
        Ordinal0 [0x003BBA34+1358388]
        Ordinal0 [0x003CBAF2+1424114]
        Ordinal0 [0x003BB806+1357830]
        Ordinal0 [0x00396086+1204358]
        Ordinal0 [0x00396F96+1208214]
        GetHandleVerifier [0x0068B232+1658114]
        GetHandleVerifier [0x0074312C+2411516]
        GetHandleVerifier [0x0057F261+560433]
        GetHandleVerifier [0x0057E366+556598]
        Ordinal0 [0x0048286B+2173035]
        Ordinal0 [0x004875F8+2192888]
        Ordinal0 [0x004876E5+2193125]
        Ordinal0 [0x004911FC+2232828]
        BaseThreadInitThunk [0x7639FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77A97A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77A97A6E+238]

**Comment by Levitans** [comment]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[class="course-list"]"}，这个报错就是在你的页面上没有个class="course-list"这个元素。学校不一样学习通的一面不是很通用。你可以按照使用说明里面的第4点来做

**Comment by 447238862** [comment]
name = i.find_element(By.CSS_SELECTOR, '[class="color1"]').text  这个元素对应什么参数的

**Comment by Levitans** [comment]
这句的作用就是找到课程的名称。你学习通的网页中课程名称的标签class不一定是"color1"

**Comment by xcmask** [comment]
name 'xuexitong' is not defined为啥呀
