### ISSUE TITLE
请问这是怎么回事，应该怎么办

### ISSUE THREAD

**Issue by 19819068211** [Levitans/XueXiTongAutoFlush#9]
Traceback (most recent call last):
  File "C:\Users\jl\XueXiTongAutoFlush\main.py", line 156, in <module>
    xueXiTong.work()
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\xueXiTong.py", line 96, in work
    chapterList = self.__school.getChapter()
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\school.py", line 85, in getChapter
    self.__driver.switch_to.frame(iframeList[-1])
IndexError: list index out of range
![屏幕截图(68)](https://user-images.githubusercontent.com/66981884/159103970-f488dd9a-f7d9-42a7-9907-cfa85c290c2e.png)

**Comment by Levitans** [comment]
你这个是进入课程后不是新版的问题，程序根据新版来做的所以旧版本会出问题。晚点会加上判断版本的操作，你之后在试试

**Comment by 19819068211** [comment]
[91m程序初始化异常[39m
配置文件路径：.\config.ini
读取配置失败：section="other", option="exception_log_file_path"
错误信息：No section: 'other'


请问这应该怎么处理，谢谢

**Comment by Levitans** [comment]
config.ini中有新加东西，我忘记上传了。现在可以了
